name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.4.1
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  http: ^0.13.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  share_plus: ^6.3.1
